CREATE USER MOVIE_MANAGER
  IDENTIFIED BY "12345678"
  DEFAULT TABLESPACE USERS
  QUOTA UNLIMITED ON users
;
GRANT CREATE SESSION TO MOVIE_MANAGER;
GRANT CREATE TABLE TO MOVIE_MANAGER;
GRANT CREATE VIEW TO MOVIE_MANAGER;
GRANT CREATE SEQUENCE TO MOVIE_MANAGER;
GRANT CREATE PROCEDURE TO MOVIE_MANAGER;
GRANT CREATE TRIGGER TO MOVIE_MANAGER;
GRANT CREATE TYPE TO MOVIE_MANAGER;
